/**
 * Selectors for mod_kanban.
 */
export default {
    ADDCARD: `[data-action="add_card"]`,
    ADDCARDCONTAINER: `.mod_kanban_addcard_container`,
    ADDCARDFIRST: `.mod_kanban_addcard_first`,
    ADDCOLUMN: `[data-action="add_column"]`,
    ADDCOLUMNCONTAINER: `.mod_kanban_addcolumn_container`,
    ADDCOLUMNFIRST: `.mod_kanban_addcolumn_first`,
    ASSIGNEES: `.mod_kanban_assignees`,
    ASSIGNSELF: `[data-action="assign_self"]`,
    ASSIGNUSER: `[data-action="assign_user"]`,
    ASSIGNEDUSER: `.mod_kanban_assigned_user`,
    BOARD: `.mod_kanban_board`,
    CARD: `.mod_kanban_card`,
    COLUMN: `.mod_kanban_column`,
    COLUMNCONTAINER: `.mod_kanban_column_container`,
    COLUMNINNER: `.mod_kanban_column_inner`,
    COMPLETE: `[data-action="complete_card"]`,
    COMPLETIONSTATE: `.mod_kanban_card_completion`,
    CONTAINER: `.mod_kanban_render_container`,
    DELETEBOARD: `[data-action="delete_board"]`,
    DELETECARD: `[data-action="delete_card"]`,
    DELETECOLUMN: `[data-action="delete_column"]`,
    DELETEMESSAGE: `[data-action="delete_message"]`,
    DELETETEMPLATE: `[data-action="delete_template"]`,
    DESCRIPTIONMODAL: `.mod_kanban_description`,
    DESCRIPTIONMODALBODY: `.mod_kanban_description_modal .modal-body`,
    DESCRIPTIONMODALFOOTER: `.mod_kanban_description_modal .modal-footer`,
    DESCRIPTIONMODALTITLE: `.mod_kanban_description_modal .modal-title`,
    DESCRIPTIONTOGGLE: `.mod_kanban_description`,
    DISCUSSION: `.mod_kanban_discussion`,
    DISCUSSIONINPUT: `.mod_kanban_discussion_input`,
    DISCUSSIONMESSAGES: `.mod_kanban_discussion_messages`,
    DISCUSSIONMODAL: `.mod_kanban_discussion_modal`,
    DISCUSSIONMODALTITLE: `.mod_kanban_discussion_modal .modal-title`,
    DISCUSSIONMODALTRIGGER: `.mod_kanban_discussion_trigger`,
    DISCUSSIONSEND: `[data-action="send_discussion_message"]`,
    DISCUSSIONSHOW: `[data-action="show_discussion"]`,
    DUEDATE: `.mod_kanban_duedate`,
    EDITDETAILS: `[data-action="edit_details"]`,
    HIDEHIDDEN: `[data-action="hide_hidden"]`,
    HISTORY: `.mod_kanban_history`,
    HISTORYITEMS: `.mod_kanban_history_items`,
    HISTORYMODAL: `.mod_kanban_history_modal`,
    HISTORYMODALTRIGGER: `[data-action="show_history"]`,
    INPLACEEDITABLE: `.inplaceeditable`,
    LOCKCOLUMN: `[data-action="lock_column"]`,
    LOCKBOARDCOLUMNS: `[data-action="lock_board_columns"]`,
    MAIN: `.mod_kanban_main`,
    MOVECARDAFTERCARD: `.mod_kanban_move_card_aftercard`,
    MOVECARDCOLUMN: `.mod_kanban_move_card_column`,
    MOVEMODALTRIGGER: `[data-action="move_card"]`,
    PUSHCARD: `[data-action="push_card"]`,
    SAVEASTEMPLATE: `[data-action="create_template"]`,
    SCROLLLEFT: `.mod_kanban_scroll_left button`,
    SCROLLRIGHT: `.mod_kanban_scroll_right button`,
    SHOWBOARD: `[data-action="show_board"]`,
    SHOWHIDDEN: `[data-action="show_hidden"]`,
    SHOWTEMPLATE: `[data-action="show_template"]`,
    UNASSIGNSELF: `[data-action="unassign_self"]`,
    UNASSIGNUSER: `[data-action="unassign_user"]`,
    UNCOMPLETE: `[data-action="uncomplete_card"]`,
    UNLOCKCOLUMN: `[data-action="unlock_column"]`,
    UNLOCKBOARDCOLUMNS: `[data-action="unlock_board_columns"]`,
};