/**
 * Selectors for mod_kanban.
 */
export default {
    ADDCARD: `[data-action="add_card"]`,
    ADDCARDCONTAINER: `.mod_kanban_addcard_container`,
    ADDCARDFIRST: `.mod_kanban_addcard_first`,
    ADDCOLUMN: `[data-action="add_column"]`,
    ADDCOLUMNCONTAINER: `.mod_kanban_addcolumn_container`,
    ADDCOLUMNFIRST: `.mod_kanban_addcolumn_first`,
    ASSIGNEES: `.mod_kanban_assignees`,
    ASSIGNSELF: `[data-action="assign_self"]`,
    ASSIGNUSER: `[data-action="assign_user"]`,
    ASSIGNEDUSER: `.mod_kanban_assigned_user`,
    BOARD: `.mod_kanban_board`,
    CARD: `.mod_kanban_card`,
    COLUMN: `.mod_kanban_column`,
    COLUMNINNER: `.mod_kanban_column_inner`,
    COMPLETE: `[data-action="complete_card"]`,
    COMPLETIONSTATE: `.mod_kanban_card_completion`,
    CONTAINER: `.mod_kanban_render_container`,
    DELETECARD: `[data-action="delete_card"]`,
    DELETECOLUMN: `[data-action="delete_column"]`,
    DESCRIPTIONMODAL: `.mod_kanban_description`,
    DESCRIPTIONMODALBODY: `.mod_kanban_description_modal .modal-body`,
    DESCRIPTIONMODALTITLE: `.mod_kanban_description_modal .modal-title`,
    DESCRIPTIONTOGGLE: `.mod_kanban_description`,
    DUEDATE: `.mod_kanban_duedate`,
    EDITDETAILS: `[data-action="edit_details"]`,
    INPLACEEDITABLE: `.inplaceeditable`,
    LOCKCOLUMN: `[data-action="lock_column"]`,
    UNASSIGNSELF: `[data-action="unassign_self"]`,
    UNASSIGNUSER: `[data-action="unassign_user"]`,
    UNCOMPLETE: `[data-action="uncomplete_card"]`,
    UNLOCKCOLUMN: `[data-action="unlock_column"]`,
};